/**
 * Utility for merging YAML frontmatter when updating existing notes.
 *
 * Problem: The plugin's nunjucks template engine overwrites the entire file
 * content, including the YAML frontmatter. This destroys any custom properties
 * the user has manually added in Obsidian.
 *
 * Solution: Extract frontmatter from both the existing file and the newly
 * rendered template, then merge them at the top-level key granularity.
 * - User-added keys (not present in the template output) are preserved.
 * - Keys generated by the template overwrite matching keys in the old file.
 */

/**
 * Extract the YAML frontmatter block (between the first pair of --- delimiters)
 * from markdown content. Returns the raw YAML string or empty string.
 */
export function extractFrontmatterBlock(content: string): string {
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  return match ? match[1] : '';
}

/**
 * Remove the frontmatter block from content, returning just the body.
 */
export function removeFrontmatter(content: string): string {
  const match = content.match(/^---\n[\s\S]*?\n---\n?/);
  return match ? content.slice(match[0].length) : content;
}

/**
 * Given a YAML frontmatter string, parse it into a Map of top-level keys
 * to their raw YAML block (including the key line and all indented sub-lines).
 *
 * This preserves the exact formatting of nested structures so we can
 * reconstruct the YAML without introducing whitespace or quoting changes.
 */
function parseTopLevelYamlBlocks(yaml: string): Map<string, string> {
  const result = new Map<string, string>();
  const lines = yaml.split('\n');
  let currentKey: string | null = null;
  let currentBlock: string[] = [];

  for (const line of lines) {
    // A top-level YAML key: starts at column 0, is not empty, and contains ':'
    // The key is everything before the first ':'.
    const isEmpty = /^\s*$/.test(line);
    const isIndented = /^\s/.test(line);

    if (!isEmpty && !isIndented && line.includes(':')) {
      // Save the previous key's block
      if (currentKey !== null) {
        result.set(currentKey, currentBlock.join('\n'));
      }

      // Start a new top-level key
      const colonIdx = line.indexOf(':');
      currentKey = line.slice(0, colonIdx).trim();
      currentBlock = [line];
    } else if (currentKey !== null) {
      // Continuation of the current top-level key (indented lines, empty lines
      // between blocks, etc.)
      currentBlock.push(line);
    }
    // else: lines before the first top-level key (e.g. leading blank lines) are
    // skipped
  }

  // Save the last key
  if (currentKey !== null) {
    result.set(currentKey, currentBlock.join('\n'));
  }

  return result;
}

/**
 * Merge old and new frontmatter.
 * - Keys that exist only in the old frontmatter are preserved (user-added).
 * - Keys that exist in the new frontmatter overwrite the old value.
 * - Keys that exist only in the new frontmatter are added.
 */
function mergeTopLevelYaml(oldYaml: string, newYaml: string): string {
  const oldBlocks = parseTopLevelYamlBlocks(oldYaml);
  const newBlocks = parseTopLevelYamlBlocks(newYaml);

  // Start with old keys to preserve user-added properties,
  // then overwrite with new template-generated keys.
  const merged = new Map<string, string>(oldBlocks);
  for (const [key, block] of newBlocks) {
    merged.set(key, block);
  }

  // Reconstruct the YAML string, preserving original key ordering as much as possible:
  // old keys first, then new keys appended at the end.
  const outputLines: string[] = [];
  for (const [key, block] of merged) {
    outputLines.push(block);
  }

  return outputLines.join('\n');
}

/**
 * Merge the frontmatter of an existing note with newly rendered content.
 *
 * @param existingContent - The full markdown content of the existing note.
 * @param newContent - The full markdown content generated by the template.
 * @returns The merged markdown content: old custom YAML keys preserved,
 *          template YAML keys updated, and new body.
 */
export function mergeFrontmatterContent(
  existingContent: string,
  newContent: string
): string {
  const oldYaml = extractFrontmatterBlock(existingContent);
  const newYaml = extractFrontmatterBlock(newContent);

  // If the new content has no frontmatter, there's nothing to merge.
  if (!newYaml) {
    return newContent;
  }

  // If the old content has no frontmatter, just use the new content as-is.
  if (!oldYaml) {
    return newContent;
  }

  const mergedYaml = mergeTopLevelYaml(oldYaml, newYaml);
  const newBody = removeFrontmatter(newContent);

  // Reconstruct: merged frontmatter + new body
  return `---\n${mergedYaml}\n---\n${newBody}`;
}
